### ISSUE TITLE
Crates.io jira

### ISSUE THREAD

**Issue by hdost** [MrRefactoring/jira#1]
👋🏼 it looks as if you're occupying the jira path on crates.io I was wondering if you would be able to cede that name to be since it doesn't look like it's being used. 

https://github.com/hdost/jira-rust is what I plan to put there.

**Comment by MrRefactoring** [comment]
Hi @hdost! I was planning on developing a library for Rust, but so far I'm stuck developing a similar version for TypeScript, along with support for several other libraries for Atlassian.

So I think it's only fair to give you this repository and name. Can you tell me how I can do that?

**Comment by hdost** [comment]
https://crates.io/crates/jira/owners < You'd just need to add me here.

**Comment by MrRefactoring** [comment]
I send an invite for you
